-- Suppression des tables si elles existent (Nettoyage)
-- DROP TABLE loans;
-- DROP TABLE books;
-- DROP TABLE clients;
-- DROP TABLE app_users;

-- 1. TABLE USERS (Admin / Staff)
CREATE TABLE app_users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) NOT NULL,
    password VARCHAR2(100) NOT NULL, 
    role VARCHAR2(20) CHECK (role IN ('ADMIN', 'STAFF')),
    email VARCHAR2(100)
);

DELETE FROM app_users WHERE id = 1;
SELECT * from app_users;


-- 2. TABLE CLIENTS (Avec Score & Blacklist)
CREATE TABLE clients (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR2(100) NOT NULL,
    cin VARCHAR2(20) UNIQUE,
    phone VARCHAR2(20),
    score NUMBER DEFAULT 100,
    is_blacklisted VARCHAR2(1) DEFAULT 'N' CHECK (is_blacklisted IN ('Y', 'N'))
);

-- 3. TABLE BOOKS
CREATE TABLE books (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR2(200) NOT NULL,
    author VARCHAR2(100),
    category VARCHAR2(50),
    stock NUMBER DEFAULT 0,
    total_qty NUMBER DEFAULT 0,
    CONSTRAINT chk_stock CHECK (stock >= 0)
);

SELECT * FROM books;

-- 4. TABLE LOANS (Emprunts)
CREATE TABLE loans (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id NUMBER,
    client_id NUMBER,
    date_out DATE DEFAULT SYSDATE,
    date_return DATE,
    status VARCHAR2(20) DEFAULT 'ACTIVE' CHECK (status IN ('ACTIVE', 'RETURNED')),
    CONSTRAINT fk_book FOREIGN KEY (book_id) REFERENCES books(id),
    CONSTRAINT fk_client FOREIGN KEY (client_id) REFERENCES clients(id)
);

-- 5. TRIGGER : GESTION AUTOMATIQUE DU STOCK
-- Ce trigger diminue le stock à la sortie et l'augmente au retour
CREATE OR REPLACE TRIGGER trg_manage_stock
AFTER INSERT OR UPDATE ON loans
FOR EACH ROW
BEGIN
    -- Cas 1: Sortie d'un livre (INSERT)
    IF INSERTING THEN
        UPDATE books 
        SET stock = stock - 1 
        WHERE id = :NEW.book_id;
    END IF;

    -- Cas 2: Retour d'un livre (UPDATE status to RETURNED)
    IF UPDATING THEN
        IF :OLD.status = 'ACTIVE' AND :NEW.status = 'RETURNED' THEN
            UPDATE books 
            SET stock = stock + 1 
            WHERE id = :NEW.book_id;
        END IF;
    END IF;
END;
/

INSERT INTO books (title, author, category, stock, total_qty) VALUES
('Clean Code', 'Robert C. Martin', 'Programming', 5, 5),
('The Pragmatic Programmer', 'Andrew Hunt & David Thomas', 'Programming', 4, 4),
('JavaScript: The Good Parts', 'Douglas Crockford', 'Programming', 3, 3),
('You Don’t Know JS', 'Kyle Simpson', 'Programming', 6, 6),
('Introduction to Algorithms', 'Thomas H. Cormen', 'Algorithms', 2, 2),
('Design Patterns', 'Erich Gamma', 'Software Engineering', 4, 4),
('Code Complete', 'Steve McConnell', 'Programming', 5, 5),
('Deep Work', 'Cal Newport', 'Productivity', 3, 3),
('Atomic Habits', 'James Clear', 'Self Development', 7, 7),
('Thinking, Fast and Slow', 'Daniel Kahneman', 'Psychology', 4, 4),
('The Lean Startup', 'Eric Ries', 'Business', 5, 5),
('Rich Dad Poor Dad', 'Robert Kiyosaki', 'Business', 6, 6),
('Harry Potter and the Sorcerer''s Stone', 'J.K. Rowling', 'Fantasy', 8, 8),
('The Lord of the Rings', 'J.R.R. Tolkien', 'Fantasy', 3, 3),
('1984', 'George Orwell', 'Novel', 5, 5),
('To Kill a Mockingbird', 'Harper Lee', 'Novel', 4, 4),
('The Alchemist', 'Paulo Coelho', 'Novel', 6, 6),
('Sapiens', 'Yuval Noah Harari', 'History', 3, 3),
('The Psychology of Money', 'Morgan Housel', 'Finance', 5, 5),
('Cracking the Coding Interview', 'Gayle Laakmann McDowell', 'Programming', 4, 4);



COMMIT;